### ISSUE TITLE
Unable to load pdf

### ISSUE THREAD

**Issue by eqan** [NeverBehave/compile-overleaf#23]
As per your documentation I had added the share token to the test.js but it is redirecting me to the github repo and putting the token along side the website URL also doesn't reveal the pdf either but gives the error as below.

![image](https://user-images.githubusercontent.com/61124752/169411207-b2ce6462-b5eb-4894-99b4-272df29fe0a9.png)

Could you please elaborate how we can view the document using a URL like: https://www.overleaf.com/read/vbwkxyryybkd

**Comment by NeverBehave** [comment]
https://compile-overleaf.vercel.app/api/read?token=vbwkxyryybkd

https://compile-overleaf.vercel.app/#vbwkxyryybkd

No issue as far as I can tell

**Comment by eqan** [comment]
Also one more thing will the resume update on the compile-site when I update it on overleaf because seemingly this isn't updating

**Comment by NeverBehave** [comment]
> Also one more thing will the resume update on the compile-site when I update it on overleaf because seemingly this isn't updating

Yes it will, the cache is 1200s to prevent frequent fetching/compiling.

**Comment by eqan** [comment]
Got it to thank you so much and really appreciate your efforts in making such a unique project
